### ISSUE TITLE
Nav menu is not responsive

### ISSUE THREAD

**Issue by chuckdries** [dcrobotics/DCR-Website-Redesign#1]
I tried using an off-the-shelf javascript solution and it just didn't work. Are options from here are as follows:
- Javascript to show and hide the `<nav>` element with the click of a button
- Pure CSS as demonstrated [here](http://codepen.io/andreasstorm/pen/lriga)

I think I'm going to give the CSS approach a shot, but later. Not right now.

From now on, we should use the github issue tracker to keep a todo list of sorts so we can all know who's doing what and what still needs to be done.

**Comment by dkuhler** [comment]
Yes, lets use the issue tracker for a todo list.

**Comment by chuckdries** [comment]
# Progress Tracker:
- [x] _Pure CSS_ solution to show and hide menu
- [x] top bar looks good at all screen sizes in menu-hidden state
- [x] top bar looks good at all screen sizes in menu-shown state
- [x] child-menus look good and are clearly related to their parents

**Comment by chuckdries** [comment]
## Update 1:

The menu itself shows and hides when appropriate, but looks like garbage.

_Relevant code has been pushed to branch `css-responsive-nav`_
